[versions]
activity = "1.9.3"
agp = "8.8.0-rc02"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
fragment = "1.8.5"
gson = "2.11.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.0"
lifecycle = '2.8.7'
material = "1.12.0"
room = "2.6.1"
uiAndroid = "1.7.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-viewmodel-ktx = {group= "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle"}
androidx-lifecycle-livedata-ktx = {group= "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.9.0" }
com-google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
composeloading = { group = "com.github.commandiron", name = "ComposeLoading", version = "1.0.4" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiAndroid" }
androidx-compose-material = { group = "androidx.compose.material3", name = "material3", version = "1.3.1" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

